### ISSUE TITLE
Client Not Getting Up: "This relative module was not found:   | * ./src/main.js in multi (webpack)-dev-server/client?http://localhost:8080  webpack/hot/dev-server ./src/main.js"

### ISSUE THREAD

**Issue by karstengresch** [itp-world/blockchain-otc-dapp#5]
For - ongoing - documentation purposes...

### Problem

When following the documentation under [openshift/README.md](https://github.com/itp-world/blockchain-otc-dapp/tree/master/openshift/README.md), i.e. creating an OpenShift project and installing parity, client and server as so...

```
oc new-project demo

oc create -f blockchain-app-template.yml
oc create -f parity-template.yml

oc new-app blockchain-app
oc new-app parity
```
... the pods come up, but the client app is not available (TBD, perhaps @siamaksade or @LutzLange : correct health checks needed.).

Pod log reports a problem with webpack:
```
Environment:
--
  | DEV_MODE=false
  | NODE_ENV=production
  | DEBUG_PORT=5858
  | Launching via npm...
  | npm info it worked if it ends with ok
  | npm info using npm@5.6.0
  | npm info using node@v8.9.4
  | npm info lifecycle otc-parity-client@1.0.0~prestart: otc-parity-client@1.0.0
  | npm info lifecycle otc-parity-client@1.0.0~start: otc-parity-client@1.0.0
  | > otc-parity-client@1.0.0 start /opt/app-root/src
  | > npm run dev
  | npm info it worked if it ends with ok
  | npm info using npm@5.6.0
  | npm info using node@v8.9.4
  | npm info lifecycle otc-parity-client@1.0.0~predev: otc-parity-client@1.0.0
  | npm info lifecycle otc-parity-client@1.0.0~dev: otc-parity-client@1.0.0
  | > otc-parity-client@1.0.0 dev /opt/app-root/src
  | > webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
  | ERROR  Failed to compile with 2 errors14:57:34
  | This dependency was not found:
  | * /opt/app-root/src/node_modules/webpack-dev-server/client/index.js?http://localhost:8080  in multi (webpack)-dev-server/client?http://localhost:8080  webpack/hot/dev-server ./src/main.js
  | To install it, you can run: npm install --save /opt/app-root/src/node_modules/webpack-dev-server/client/index.js?http://localhost:8080
  | This relative module was not found:
  | * ./src/main.js in multi (webpack)-dev-server/client?http://localhost:8080  webpack/hot/dev-server ./src/main.js
```

### Assumed Root Cause: Missing Resolution for /opt/app-root/src/src/main.js

Initial research:

```
oc get pod
oc rsh <pod name>
sh-4.2$echo $PATH
/opt/rh/rh-nodejs8/root/usr/bin:/opt/app-root/src/node_modules/.bin/:/opt/app-root/src/.npm-global/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

#### Nr. 1: Extend $PATH to /opt/app-root/src/src/
TBC...

**Comment by karstengresch** [comment]
Continued...

## Nr. 1: Extend $PATH to /opt/app-root/src/src/

### Trying to change the PATH value in openshift/blockchain-app-template.yml

  * Tried in _sourceStrategy_

    
```
strategy:
      sourceStrategy:
        env:
        - name: NPM_MIRROR
          value: ${NPM_MIRROR}
        - name: DEV_MODE
          value: "false"
        - name: PATH
          value: "$PATH:/opt/app-root/src/src/"
```

Result: failed (i.e. PATH not appended (checked via `echo $PATH` in pod terminal) file not found), as it is not a tweakable environment variable for the image.

Same result in terminal (also for subsequent tries):

```
sh-4.2$ echo $PATH
/opt/rh/rh-nodejs8/root/usr/bin:/opt/app-root/src/src:/opt/app-root/src:/opt/app-root/src/node_modules/.bin/:/opt/app-root/src/.npm-global/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
```

NB - `/opt/app-root/src/src`is in $PATH, but node doesn't seem to know this...???

* Same, but with _dockerStrategy_: 

 ```
     dockerStrategy:
        env:
        - name: "PATH"
          value: "$PATH:/opt/app-root/src/src/"
```

Result: failed (i.e. PATH not appended (checked via `echo $PATH` in pod terminal) file not found, s.a.).

  * Tried, but putting PATH into curly braces (for all previous and subsequent tries), e.g.

```
      dockerStrategy:
        env:
        - name: "PATH"
          value: "${PATH}:/opt/app-root/src/src/"
```

Result: failed (i.e. PATH not appended (checked via `echo $PATH` in pod terminal) file not found, s.a.).


  * Tried w/ _recreateParams_


 ```
  recreateParams: 
        pre:  
          failurePolicy: Abort
          execNewPod:
            containerName: ${NAME}-client 
            command: [ "export", "PATH=${PATH}:/opt/app-root/src/src/" ] 
```

Result: failed (i.e. PATH not appended (checked via `echo $PATH` in pod terminal) file not found, s.a.).

### Trying to change the PATH value in node config files

  * _build/webpack.base.conf.js_

```
module.exports = {
  context: path.resolve(__dirname, '../'),
  entry: {
    app: '/opt/app-root/src/src/main.js'
  },
```

Result: failed (i.e. PATH not appended (checked via `echo $PATH` in pod terminal) file not found, s.a.).

  * Switched NODE_ENV in to _dev_

```
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'dev'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
```

Result: failed (i.e. PATH not appended (checked via `echo $PATH` in pod terminal) file not found, s.a.).

@siamaksade, @LutzLange, @drmartinberger - I'm running out of ideas. Any helpful comments, any hook I could use before node gets started so one could append the PATH here?

Any ugly copy mechanisms to leverage?
